### ISSUE TITLE
Take the command from LLM and run the application

### ISSUE THREAD

**Issue by yashtilala412** [yashtilala412/capstone_project#5]

**Comment by arjunkukadiya13** [comment]
`
def groq_model_call(prompt):
    chat_completion = client.chat.completions.create(
            messages=[
                {
                    "role":"system",
                    "content":"In the application there is error give me the best suitable solution for the error."
                },
                {
                    "role": "user",
                    "content": prompt,
                }
            ],
            model="llama3-8b-8192",
        )
        # Extract the response from the model
    response = chat_completion.choices[0].message.content
    print(response)
    return response
`
take the command from LLM model
